name: Update Sitemap

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 17:00 in China Standard Time (09:00 UTC)

jobs:
  update_sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any Python dependencies

    - name: Run Python script to update sitemap
      run: python generate_sitemap.py  # Assuming your Python script is named generate_sitemap.py

    - name: Commit and push updated sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "Auto-update sitemap.xml"
        git push
